# Gunakan base image dengan Miniconda
FROM continuumio/miniconda3:latest

# Tentukan direktori di datalm container
WORKDIR /app

# salin semua file project ke dalam container
RUN conda env create -f conda.yaml

# Aktfikan shell dengan conda environment
SHELL ["conda", "run", "-n", "mlflow-env", "/bin/bash", "-c"]

# Deklarasikan port yang akan digunakan
EXPOSE 5005

# Jalankan script modelling.py saat container dijalankan
CMD ["conta", "run", "-n", "mlflow-env", "python", "modelling.py"]